---
# vars file for roles/sensor_ids
home_dir: < your home dir >
zeek_git: https://github.com/zeek/zeek
zeek_git_path: "{{ home_dir }}/zeek"
zeek_policy_path: /usr/local/zeek/share/zeek/site/
zeek_config_path: /usr/local/zeek/etc/
zeek_install_path: /usr/local/zeek
sniff_interface: < your interface >
log_location: "{{ home_dir }}/logs"
zeek_log_location: "{{ log_location }}/zeek/logs/current"
suricata_rule_path: /var/lib/suricata/rules
siem_ip: < your siem ip >

packages:
- cmake
- make
- gcc
- g++
- flex
- bison
- libpcap-dev
- libssl-dev
- python3-dev
- swig
- zlib1g-dev
- rustc
- cargo
- libpcre3
- libpcre3-dbg
- libpcre3-dev
- build-essential
- autoconf
- automake
- libkqueue-dev
- libtool
- libpcap-dev
- libnet1-dev
- libyaml-0-2
- libyaml-dev
- zlib1g-dev
- libcap-ng-dev
- libcap-ng0
- libmagic-dev
- libjansson-dev
- libjansson4
- pkg-config
- libnetfilter-queue-dev
- libnetfilter-queue1
- libnfnetlink-dev
- libnfnetlink0
- libmaxminddb0
- libmaxminddb-dev
- mmdb-bin
- suricata
